import { converterData, formatCPF, formatCEP } from '../../utils/fuctions';

export const Contrato = (data) => ({
    id: data?.id,
    nome: data?.nome,
    cpf: data?.cpf,
    rg: data?.rg,
    contrato: data?.contrato,
    genero: data?.genero,
    data_nascimento: data?.dataNascimento,
    religiao: data?.religiao,
    uf: data?.uf,
    naturalidade: data?.naturalidade,
    nacionalicade: data?.nacionalicade,
    profissao: data?.profissao,
    estado_civil: data?.estadoCivil,
    data_contrato: data?.dataContrato,
    is_carencia: data?.carencia,
    data_inicio_carencia: data?.dataInicioCarencia,
    data_final_carencia: data?.dataFimCarencia,
    is_cremacao: data?.isCremacao,
    data_cremacao: data?.dataCremacao,
    cep_residencia: data?.cepResidencia,
    uf_residencia: data?.ufResidencia,
    municipio_residencia: data?.municipioResidencia,
    bairro_residencia: data?.bairroResidencia,
    quadra_residencia: data?.quadraResidencia,
    lote_residencia: data?.loteResidencia,
    numero_residencia: data?.numeroResidencia,
    tipo_residencia: data?.tipoResidencia,
    rua_residencia: data?.ruaResidencia,
    complemento_residencia: data?.complementoResidencia,
    cep_comercial: data?.cepComercial,
    uf_comercial: data?.ufComercial,
    municipio_comercial: data?.municipioComercial,
    bairro_comercial: data?.bairroComercial,
    quadra_comercial: data?.quadraComercial,
    lote_comercial: data?.loteComercial,
    numero_comercial: data?.numeroComercial,
    tipo_comercial: data?.tipoComercial,
    rua_comercial: data?.ruaComercial,
    complemento_comercial: data?.complementoComercial,
    dia_pagamento: data?.diaPagamento,
    primeira_parcela: data?.primeiraParcela,
    ordem_rota: data?.ordemRota,
    contrato_cobranca: data?.contratoCobranca,
    plano: data?.plano,
    regiao: data?.regiao,
    is_transferido: data?.isTransferido,
    is_pagou_adesao: data?.isPagouAdesao,



});